#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$ROOT_DIR/config/remote_gpu_client.env"
HOST=""
USER_NAME="${USER:-}"
REMOTE_ROOT=""
PORT="22"
IDENTITY_FILE=""

usage() {
  cat <<'EOF'
Usage:
  configure_remote_gpu_client.sh --host HOST --user USER --remote-root PATH
      [--port 22] [--identity-file ~/.ssh/id_ed25519]

Writes the ignored, laptop-local config/remote_gpu_client.env file.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --user) USER_NAME="$2"; shift 2 ;;
    --remote-root) REMOTE_ROOT="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --identity-file) IDENTITY_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$HOST" || -z "$USER_NAME" || -z "$REMOTE_ROOT" ]]; then
  echo "--host, --user and --remote-root are required" >&2
  usage >&2
  exit 2
fi
if [[ "$HOST" == *$'\n'* || "$USER_NAME" == *$'\n'* || "$REMOTE_ROOT" == *$'\n'* ]]; then
  echo "configuration values may not contain newlines" >&2
  exit 2
fi
if ! [[ "$PORT" =~ ^[0-9]+$ ]] || (( PORT < 1 || PORT > 65535 )); then
  echo "--port must be between 1 and 65535" >&2
  exit 2
fi

umask 077
{
  printf '%s\n' \
    '# Generated by scripts/configure_remote_gpu_client.sh; never commit this file.' \
    'A1Z_REAL_VISION_BACKEND=remote_ssh'
  printf 'A1Z_REMOTE_GPU_HOST=%s\n' "$HOST"
  printf 'A1Z_REMOTE_GPU_USER=%s\n' "$USER_NAME"
  printf 'A1Z_REMOTE_GPU_PORT=%s\n' "$PORT"
  printf 'A1Z_REMOTE_GPU_ROOT=%s\n' "$REMOTE_ROOT"
  printf 'A1Z_REMOTE_GPU_IDENTITY_FILE=%s\n' "$IDENTITY_FILE"
  printf '%s\n' \
    'A1Z_REMOTE_GPU_TIMEOUT_S=900' \
    'A1Z_REMOTE_GPU_CONNECT_TIMEOUT_S=10' \
    'A1Z_REMOTE_GPU_STRICT_HOST_KEY_CHECKING=accept-new'
} > "$OUTPUT"

chmod 600 "$OUTPUT"
echo "Wrote $OUTPUT"
echo "Next: $ROOT_DIR/scripts/run_remote_vision_job.py preflight"
